name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.19.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.APP_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Automated release by GitHub Actions
        draft: false
        prerelease: false

    - name: Upload APK
      id: upload_apk
      uses: actions/upload-artifact@v2
      with:
        name: Starkmarkdown
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Add APK to release
      id: add_to_release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.APP_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.upload_apk.outputs.artifact_path }}
        asset_name: starkmarkdown-${{ github.sha }}.apk
        asset_content_type: application/vnd.android.package-archive
